[package]
name = "mk-engine"
description = "Game logic â€” validate, execute, effects, valid_actions"
version.workspace = true
edition.workspace = true

[dependencies]
mk-types = { workspace = true }
mk-data = { workspace = true }
serde = { workspace = true }
arrayvec = { workspace = true }

[dev-dependencies]
serde_json = "1.0"
